### PR TITLE
Tooltip 

### PR DESCRIPTION
**Pull request by swongg**
- add tooltip next to input boxes on create secret message page #65 
- update alignment of textarea and update sizing

question icon:
image

### CODE REVIEW

**Review by tamf — COMMENTED** [review]
Looks good! Could we add a bit of space between the tooltip and entry box so they aren't touching? And also move it down so it's centered with the box

**Comment by tamf** [comment]
Sorry, had to force fix a previous commit on master. Pls rebase

**Comment by tamf** [comment]
@swongg if you have updated the alignment of the tooltip icon, can you update the screenshot in the description?

**Comment by swongg** [comment]
> @swongg if you have updated the alignment of the tooltip icon, can you update the screenshot in the description?
updated

**Comment by swongg** [comment]
tooltip has been aligned and I've updated the image @tamf

**Review by tamf — APPROVED** [review]

**Pull request merged**
